#include "stdafx.h"
#include "VertexType.h"
vector<D3D11_INPUT_ELEMENT_DESC> Vertex::descs	// 외부에서 초기화
{
	{ "POSITION", 0, DXGI_FORMAT_R32G32_FLOAT, 0, 0, D3D11_INPUT_PER_VERTEX_DATA, 0 }
};

vector<D3D11_INPUT_ELEMENT_DESC> VertexColor::descs	// 외부에서 초기화
{
	{ "POSITION", 0, DXGI_FORMAT_R32G32_FLOAT, 0, 0, D3D11_INPUT_PER_VERTEX_DATA, 0 },
	{ "COLOR", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0, D3D11_APPEND_ALIGNED_ELEMENT, D3D11_INPUT_PER_VERTEX_DATA, 0}
};

vector<D3D11_INPUT_ELEMENT_DESC> VertexTexture::descs	// 외부에서 초기화
{
	{ "POSITION", 0, DXGI_FORMAT_R32G32_FLOAT, 0, 0, D3D11_INPUT_PER_VERTEX_DATA, 0 },
	{ "TEXCOORD", 0, DXGI_FORMAT_R32G32_FLOAT, 0, D3D11_APPEND_ALIGNED_ELEMENT, D3D11_INPUT_PER_VERTEX_DATA, 0 }	// x, y만 들어가기 떄문에 수정
};
